cvm-version: 0.7.5
memory: 16384
cpus: 8

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router@sha256:5fe59be5369e34e306f4e663fc2be7fce312b5045bf9a5d3fe1be36db1d32862" # v0.0.93
    restart: always
    env:
      - DOMAIN
      - REFRESH_INTERVAL: "1m"
      - USAGE_REPORTER_ID: "model-router"
      - CONTROL_PLANE_URL: "https://api.tinfoil.sh"
    secrets:
      - USAGE_REPORTER_SECRET
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8089/health"]
      interval: 30s
      timeout: 5s
      start_period: 5m

shim:
  upstream-port: 8089
  tls-wildcard: true
