cvm-version: 0.7.5
memory: 16384
cpus: 8

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router@sha256:08511a229ec660af15d76a34cabf98c31b3598ec97fffde465c361388ee2e658" # v0.0.83
    restart: always
    env:
      - DOMAIN
      - REFRESH_INTERVAL: "1m"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8089/health"]
      interval: 30s
      timeout: 5s
      start_period: 5m

shim:
  upstream-port: 8089
  tls-wildcard: true
