cvm-version: 0.7.3
cpus: 8
memory: 16384

shim:
  upstream-port: 8089
  tls-wildcard: true

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router@sha256:e115c1322bb6bcb1ec37d78e05ce37f940f1f51e9fab306546286fd9acb090c5" # v0.0.76
    env:
      - DOMAIN
      - REFRESH_INTERVAL: "1m"
