// Package cachesalt derives the per-request cache_salt values that partition
// vLLM's prefix cache between principals. vLLM only reuses cached KV blocks
// between requests carrying the same salt, so giving each principal its own
// salt stops other callers from probing, via response timing, whether a
// given prompt is already cached.
//
// Every derived value is a domain-tagged, length-prefixed SHA-256:
//
//	Sum(tag, f1, ..., fn) = SHA-256(tag ‖ lp(f1) ‖ ... ‖ lp(fn))
//	lp(x)                 = uint32_be(len(x)) ‖ x
//
// The length prefixes make the encoding prefix-free: no sequence of framed
// fields can be read as a different sequence, so ("org_1", "2345") and
// ("org_12345") hash differently even though they concatenate to identical
// bytes. Without this, a caller could craft a secret that lands in another
// tenant's cache namespace.
//
// Derivation is a pure function of its inputs — no keys, no per-process
// state — so every router replica computes identical salts across restarts,
// deploys, and failovers.
//
// Changing any detail (tag, framing, hash, output encoding) changes every
// salt and cold-starts every cache namespace. The construction is pinned by
// testdata/vectors.json, generated by an independent implementation; never
// regenerate that file from this package.
package cachesalt

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"math"
)

// SaltDomainTag namespaces cache_salt derivation. Tags are hashed unframed,
// so every tag must be a fixed constant and no tag may be a prefix of
// another.
const SaltDomainTag = "tinfoil/cache-salt/v1"

// Mode identifies which derivation produced a salt; it doubles as a metric
// label.
type Mode string

const (
	// ModeNone means no salt was derived and none must be injected.
	ModeNone Mode = ""
	// ModeTenant means the whole tenant shares one cache namespace.
	ModeTenant Mode = "tenant"
	// ModeUser means a user cache secret subdivides the tenant's
	// namespace per end user.
	ModeUser Mode = "user"
)

// Derive returns the cache_salt for a request: a tenant-wide namespace when
// userCacheSecret is empty, a per-user namespace within the tenant when it
// is present.
//
// tenantID must be a stable identifier for the authenticated caller (e.g.
// the verified JWT subject, or a long-lived opaque API key). Never pass a
// client-chosen value — callers could pick their namespace — and prefer a
// stable identifier over a short-lived rotating token, which would
// cold-start the caller's namespace on every refresh. Isolation is only as
// strong as the authentication that produced tenantID.
//
// If tenantID is empty there is no identity to anchor a salt to: Derive
// returns ("", ModeNone) and the caller must skip injection. An empty
// userCacheSecret distinguishes nobody and is treated as absent.
//
// The salt is the unpadded URL-safe base64 of the 32-byte digest: 43 chars,
// safe to embed in JSON, URLs, logs, and metric labels.
func Derive(tenantID, userCacheSecret string) (string, Mode) {
	if tenantID == "" {
		return "", ModeNone
	}
	var sum [sha256.Size]byte
	mode := ModeTenant
	if userCacheSecret == "" {
		sum = Sum(SaltDomainTag, tenantID)
	} else {
		sum = Sum(SaltDomainTag, tenantID, userCacheSecret)
		mode = ModeUser
	}
	return base64.RawURLEncoding.EncodeToString(sum[:]), mode
}

// Sum computes SHA-256(tag ‖ lp(field_1) ‖ ... ‖ lp(field_n)). The tag is
// hashed unframed; see SaltDomainTag for the constraint that implies.
func Sum(tag string, fields ...string) [sha256.Size]byte {
	h := sha256.New()
	h.Write([]byte(tag))
	var n [4]byte
	for _, f := range fields {
		if len(f) > math.MaxUint32 {
			// Silent truncation would break the prefix-free framing.
			panic("cachesalt: field exceeds uint32 framing limit")
		}
		binary.BigEndian.PutUint32(n[:], uint32(len(f)))
		h.Write(n[:])
		h.Write([]byte(f))
	}
	var sum [sha256.Size]byte
	h.Sum(sum[:0])
	return sum
}
